"""Unit tests for :class:`BotBlockDetector`.

Covers, using canned `HttpResponseEvidence` snapshots only: a real
successful homepage (no block), a Cloudflare challenge page (headers
+ body), a Cloudflare "Access Denied" page (headers only), an Akamai
"Reference #" block page, a generic/unbranded anti-bot page, a plain
403 error page with no anti-bot copy (must NOT be flagged), a
missing/unreachable response (no HTTP response was ever obtained), and
header case-insensitivity. This verifies detection accuracy and
graceful degradation; it performs no scoring or assertions about
Agentic Readiness.
"""

from __future__ import annotations

import sys
from pathlib import Path

# Allow running this file directly (e.g. from an IDE "Run" button) by
# ensuring the project root is importable, not just the `tests/` folder.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from models.http import HttpResponseEvidence
from tools.bot_block_detector import BotBlockDetector

URL = "https://www.example.com"


def _response(
    status_code: int,
    headers: dict[str, str] | None = None,
    content: str = "",
) -> HttpResponseEvidence:
    return HttpResponseEvidence(
        requested_url=URL,
        final_url=URL,
        status_code=status_code,
        headers=headers or {},
        content=content,
    )


def test_real_homepage_is_not_blocked() -> None:
    """A genuine 200 homepage must never be flagged as blocked."""
    response = _response(
        200,
        headers={"content-type": "text/html", "server": "nginx"},
        content="<html><head><title>Welcome</title></head><body>Hello!</body></html>",
    )

    result = BotBlockDetector(response).detect()

    assert result.blocked is False
    assert result.provider is None
    assert result.reason is None
    assert result.matched_signals == []
    assert result.status_code == 200


def test_cloudflare_challenge_page_detected() -> None:
    """A Cloudflare JS challenge page (headers + body) is detected."""
    response = _response(
        503,
        headers={"server": "cloudflare", "cf-ray": "7c1234abcd-CDG"},
        content=(
            "<html><head><title>Just a moment...</title></head>"
            "<body>Checking your browser before accessing www.example.com."
            "<div class='cf-browser-verification'>...</div></body></html>"
        ),
    )

    result = BotBlockDetector(response).detect()

    assert result.blocked is True
    assert result.provider == "cloudflare"
    assert "header:cf-ray" in result.matched_signals
    assert any("server=cloudflare" in signal for signal in result.matched_signals)
    assert result.reason is not None
    assert "Cloudflare" in result.reason


def test_cloudflare_access_denied_detected_from_headers_only() -> None:
    """A Cloudflare block page identifiable purely from headers."""
    response = _response(
        403,
        headers={"server": "cloudflare", "cf-mitigated": "challenge"},
        content="<html><body>Error 1020: Access denied</body></html>",
    )

    result = BotBlockDetector(response).detect()

    assert result.blocked is True
    assert result.provider == "cloudflare"
    assert "header:cf-mitigated" in result.matched_signals


def test_akamai_reference_block_page_detected() -> None:
    """An Akamai 'Access Denied ... Reference #' page is detected."""
    response = _response(
        403,
        headers={"server": "AkamaiGHost"},
        content=(
            "Access Denied\n"
            "You don't have permission to access "
            "\"http://www.example.com/\" on this server.\n"
            "Reference #18.abc123.1690000000.abcdef\n"
            "(generated by Akamai)"
        ),
    )

    result = BotBlockDetector(response).detect()

    assert result.blocked is True
    assert result.provider == "akamai"
    assert any("server=akamaighost" in signal for signal in result.matched_signals)
    assert "content:akamai_reference_id" in result.matched_signals
    assert result.reason is not None
    assert "Akamai" in result.reason


def test_generic_bot_block_detected() -> None:
    """An unbranded 'prove you are human' page (no vendor identity)."""
    response = _response(
        403,
        headers={"server": "nginx"},
        content=(
            "<html><body><h1>Please verify you are human</h1>"
            "<p>Our systems have detected unusual traffic from your "
            "network. Please complete the captcha to continue.</p>"
            "</body></html>"
        ),
    )

    result = BotBlockDetector(response).detect()

    assert result.blocked is True
    assert result.provider == "generic"
    assert "status_code:403" in result.matched_signals
    assert any("verify you are human" in signal for signal in result.matched_signals)


def test_plain_error_page_is_not_a_block() -> None:
    """A plain 403/503 with no anti-bot copy must NOT be flagged."""
    response = _response(
        503,
        headers={"server": "nginx"},
        content="<html><body><h1>503 Service Unavailable</h1></body></html>",
    )

    result = BotBlockDetector(response).detect()

    assert result.blocked is False
    assert result.provider is None
    assert result.matched_signals == []


def test_no_response_is_not_blocked() -> None:
    """An unreachable site (no response object) is not a 'block'."""
    result = BotBlockDetector(None).detect()

    assert result.blocked is False
    assert result.provider is None
    assert result.reason is None
    assert result.matched_signals == []
    assert result.status_code is None


def test_headers_are_matched_case_insensitively() -> None:
    """Header names/values (`Server`, `CF-Ray`, ...) are matched regardless of case."""
    response = _response(
        503,
        headers={"Server": "Cloudflare", "CF-Ray": "abc123"},
        content="Checking your browser before accessing example.com.",
    )

    result = BotBlockDetector(response).detect()

    assert result.blocked is True
    assert result.provider == "cloudflare"


if __name__ == "__main__":
    test_real_homepage_is_not_blocked()
    test_cloudflare_challenge_page_detected()
    test_cloudflare_access_denied_detected_from_headers_only()
    test_akamai_reference_block_page_detected()
    test_generic_bot_block_detected()
    test_plain_error_page_is_not_a_block()
    test_no_response_is_not_blocked()
    test_headers_are_matched_case_insensitively()
    print("All tests passed.")